source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-bourbon'
gem "middleman-navigation", :git => 'https://github.com/michaek/middleman-navigation'
gem 'builder' # For feed.xml.builder
gem 'middleman-deploy'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'rake'
gem 'rake-notes'
gem 'foundation'
gem 'redcarpet'
gem 'pry'
